export const contactFormUserTemplate = (
  name: string,
  email: string,
  message: string
) => {
  const text = `
  Hello ${name},

Thank you for reaching out to us. We have received your message and will get back to you as soon as possible.

Here are the details of your submission:

Name: ${name}
Email: ${email}
Message: 
${message}

If you need further assistance, feel free to respond to this email.

Best regards,
The Golden Feather Team
  `;

  const html = `
  <!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Thank You for Contacting Us</title>
</head>
<body>
  <p>Hello ${name},</p>

  <p>Thank you for reaching out to us. We have received your message and will get back to you as soon as possible.</p>

  <p>Here are the details of your submission:</p>

  <p><strong>Name:</strong> ${name}</p>
  <p><strong>Email:</strong> ${email}</p>
  <p><strong>Message:</strong></p>
  <p>${message}</p>

  <p>If you need further assistance, feel free to respond to this email.</p>

  <p>Best regards,<br>The Golden Feather Team</p>
</body>
</html>
  `;

  return { text, html };
};

export const contactFormAdminTemplate = (
  name: string,
  email: string,
  message: string
) => {
  const text = `
  Subject: New Contact Form Submission

Hello Admin,

You have received a new contact form submission. Here are the details:

Name: ${name}
Email: ${email}
Message:
${message}

Please review and follow up as needed
  `;

  const html = `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Contact Form Submission</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f7f7f7;
        margin: 0;
        padding: 0;
      }
      .container {
        width: 100%;
        max-width: 600px;
        margin: 20px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
      h1 {
        color: #333;
      }
      p {
        font-size: 16px;
        color: #555;
      }
      .details {
        margin-top: 20px;
      }
      .details p {
        margin: 0 0 10px;
      }
      .footer {
        margin-top: 20px;
        font-size: 12px;
        color: #888;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>New Contact Form Submission</h1>
      <p>Hello Admin,</p>
      <p>You have received a new contact form submission. Here are the details:</p>
      <div class="details">
        <p><strong>Name:</strong> ${name}</p>
        <p><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
        <p><strong>Message:</strong> ${message}</p>
      </div>
      <p>Please review and follow up as needed.</p>
      <div class="footer">
        <p>This email was generated by the TGF Tavern contact form.</p>
      </div>
    </div>
  </body>
  </html>
  `;

  return { text, html };
};
